Add support to update pr from branch name

diff --git a/bin/git-updatepr b/bin/git-updatepr
--- a/bin/git-updatepr
+++ b/bin/git-updatepr
@@ -37,10 +37,14 @@ if ! git cat-file -e "$commit_to_update" 2> /dev/null; then
   exit 1
 fi
 
-branch_name="${GIT_PILE_PREFIX:-}$(git show --no-patch --format=%f "$commit_to_update" | tr '[:upper:]' '[:lower:]')"
+
+branch_name="${commit_to_update}"
 if ! git show-ref --quiet "$branch_name"; then
-  echo "error: branch '$branch_name' doesn't exist" >&2
-  exit 1
+  branch_name="${GIT_PILE_PREFIX:-}$(git show --no-patch --format=%f "$commit_to_update" | tr '[:upper:]' '[:lower:]')"
+  if ! git show-ref --quiet "$branch_name"; then
+    echo "error: branch '$branch_name' doesn't exist" >&2
+    exit 1
+  fi
 fi
 
 worktree_dir="$(git pileworktreepath)"
@@ -105,6 +109,3 @@ if [[ "$squash" == true ]]; then
 else
   git -C "$worktree_dir" push --quiet || echo "warning: failed to push '$branch_name'" >&2
 fi
-
-git rebase --interactive --exec "git commit --no-verify --amend --fixup '$commit_to_update'" "$new_refspec"^
-git rebase --interactive --autosquash "$commit_to_update"^
